set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
option(BC_SANITIZE "Enable address/undefined-behavior sanitizers" OFF)
option(BC_BUILD_APP "Build the SDL application with externally supplied game data" OFF)
set(BC_DATA_DIR "" CACHE PATH "Prepared game data directory outside this repository")
if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
    add_compile_options(-Wall -Wextra -Wpedantic)
    # Keep assertion-based checks active in Release builds.
    add_compile_options(-UNDEBUG)
    if(BC_SANITIZE)
        add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address,undefined)
    endif()
endif()

add_library(recovered_core STATIC
    lib/recovered_core.c lib/board.c lib/game.c lib/book.c lib/adjudication.c
    lib/time_control.c lib/modem_protocol.c lib/modem_session.c lib/search_moves.c
    lib/evaluation.c lib/search.c lib/save_game.c lib/setup_board.c lib/animation.c
    lib/animation_plan.c)
target_include_directories(recovered_core PUBLIC lib)

if(BC_BUILD_APP)
    if(NOT BC_DATA_DIR)
        message(FATAL_ERROR "BC_BUILD_APP requires -DBC_DATA_DIR=/path/to/prepared-data. Original game data is not included.")
    endif()
    get_filename_component(BC_DATA_DIR "${BC_DATA_DIR}" REALPATH BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach(input assets.hpp original.hpp bitmap_fonts.hpp animation_data.hpp animation_pixels.bin opening_book.bin)
        if(NOT EXISTS "${BC_DATA_DIR}/${input}")
            message(FATAL_ERROR "BC_DATA_DIR is incomplete: missing ${input}. See docs/DATA.md.")
        endif()
    endforeach()
    if(NOT IS_DIRECTORY "${BC_DATA_DIR}/assets")
        message(FATAL_ERROR "BC_DATA_DIR is incomplete: missing assets/. See docs/DATA.md.")
    endif()
    find_package(SDL3 3.4 REQUIRED CONFIG)
    find_package(Threads REQUIRED)
    add_library(presentation STATIC lib/presentation.cpp "${BC_DATA_DIR}/original.hpp"
                "${BC_DATA_DIR}/bitmap_fonts.hpp")
    target_include_directories(presentation PUBLIC lib "${BC_DATA_DIR}")
    add_executable(battlechess src/main.cpp src/Application.cpp src/ApplicationUI.cpp
                   src/ApplicationGame.cpp src/ApplicationRender.cpp src/ApplicationChecks.cpp
                   src/GameSession.cpp src/TextDialog.cpp src/SDLHelpers.cpp src/FileDialog.cpp
                   src/hint_outline.cpp src/ComputerPlayer.cpp
                   src/AnimationHost.cpp src/SetupUI.cpp src/ResourceDialog.cpp src/QuickDrawControl.cpp
                   "${BC_DATA_DIR}/animation_data.hpp" "${BC_DATA_DIR}/assets.hpp")
    target_link_libraries(battlechess PRIVATE recovered_core presentation SDL3::SDL3 Threads::Threads)
    configure_file(resources/icon.png "${CMAKE_CURRENT_BINARY_DIR}/battlechess-icon.png" COPYONLY)
endif()

include(CTest)
if(BUILD_TESTING)
    foreach(check game adjudication save_game setup_board time_control search_moves evaluation search)
        add_executable(${check}_check tests/${check}_check.c)
        target_link_libraries(${check}_check PRIVATE recovered_core)
        add_test(NAME ${check}_recovery COMMAND ${check}_check)
    endforeach()
    add_executable(modem_session_test tests/modem_session_test.c)
    target_compile_definitions(modem_session_test PRIVATE _XOPEN_SOURCE=600 _DEFAULT_SOURCE)
    target_link_libraries(modem_session_test PRIVATE recovered_core)
    add_test(NAME modem_session_recovery COMMAND modem_session_test)
    add_executable(modem_protocol_test tests/modem_protocol_test.c)
    target_link_libraries(modem_protocol_test PRIVATE recovered_core)
    add_test(NAME modem_protocol_recovery COMMAND modem_protocol_test)
    add_executable(hint_outline_check tests/hint_outline_check.cpp src/hint_outline.cpp)
    target_include_directories(hint_outline_check PRIVATE src)
    add_test(NAME hint_outline_recovery COMMAND hint_outline_check)
    add_executable(setup_ui_check tests/SetupUICheck.cpp src/SetupUI.cpp)
    target_include_directories(setup_ui_check PRIVATE src)
    target_link_libraries(setup_ui_check PRIVATE recovered_core)
    add_test(NAME setup_ui_recovery COMMAND setup_ui_check)
    add_executable(animation_check tests/animation_check.c)
    target_link_libraries(animation_check PRIVATE recovered_core)
    add_test(NAME animation_runtime COMMAND animation_check)
    add_executable(animation_mate_test tests/animation_mate_test.c)
    target_link_libraries(animation_mate_test PRIVATE recovered_core)
    add_test(NAME animation_checkmate COMMAND animation_mate_test)
    add_executable(animation_plan_test tests/animation_plan_test.c)
    target_link_libraries(animation_plan_test PRIVATE recovered_core)
    add_test(NAME animation_graphs COMMAND animation_plan_test)
    add_executable(core_check lib/recovered_core.c)
    target_compile_definitions(core_check PRIVATE BC_SELF_TEST)
    add_test(NAME recovered_core COMMAND core_check)
    add_executable(board_check tests/board_check.cpp)
    target_link_libraries(board_check PRIVATE recovered_core)
    add_test(NAME board_recovery COMMAND board_check)

    if(BC_BUILD_APP)
        add_executable(computer_player_check tests/ComputerPlayerCheck.cpp src/ComputerPlayer.cpp)
        target_include_directories(computer_player_check PRIVATE src)
        target_link_libraries(computer_player_check PRIVATE recovered_core presentation Threads::Threads)
        add_test(NAME computer_player_recovery COMMAND computer_player_check)
        add_executable(book_check tests/book_check.c)
        target_link_libraries(book_check PRIVATE recovered_core)
        add_test(NAME original_book COMMAND book_check "${BC_DATA_DIR}/opening_book.bin")
        add_executable(resource_dialog_check tests/resource_dialog_check.cpp src/ResourceDialog.cpp
                       src/QuickDrawControl.cpp)
        target_include_directories(resource_dialog_check PRIVATE src)
        target_link_libraries(resource_dialog_check PRIVATE presentation SDL3::SDL3)
        add_test(NAME resource_dialog_recovery COMMAND resource_dialog_check)
        set_tests_properties(resource_dialog_recovery PROPERTIES ENVIRONMENT "SDL_VIDEO_DRIVER=dummy;SDL_RENDER_DRIVER=software")
        add_executable(presentation_check tests/presentation_check.cpp)
        target_link_libraries(presentation_check PRIVATE presentation)
        add_test(NAME presentation_recovery COMMAND presentation_check)
        add_test(NAME animation_integration COMMAND battlechess --data "${BC_DATA_DIR}" --animation-check)
        add_test(NAME native_smoke COMMAND battlechess --data "${BC_DATA_DIR}" --smoke --check-assets
                 --screenshot "${CMAKE_CURRENT_BINARY_DIR}/smoke.png")
        set_tests_properties(animation_integration native_smoke PROPERTIES
                             ENVIRONMENT "SDL_VIDEO_DRIVER=dummy;SDL_AUDIO_DRIVER=dummy;SDL_RENDER_DRIVER=software")
    endif()
endif()
